version: '3.3'

services:
    compiler:
        container_name: testdata-compiler
        build:
            context: ./cxt
            dockerfile: pod/haskell.dockerfile
        restart: always
        tty: true
        env_file: .env
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: compiler
            DISPLAY: ":0"
        ports:
            #- "${EXT_PORT}:${INT_PORT}"
            - "3000:3000"
        volumes:
            - ./src:/root/project
            - ./var/stack-work:/root/project/.stack-work
            - ./var/stack:/root/.stack
            - /home/dragonfly/.Xauthority:/root/.Xauthority
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ./cxt/cnf/script:/root/script
        cap_add:
            - SYS_PTRACE
        networks:
            - networktestdata
        #entrypoint:
        #    - bin/bash
        #    - -i

    persistence:
        container_name: testdata-persistence
        build:
            context: ./cxt
            dockerfile: pod/postgresql.dockerfile
        restart: always
        tty: true
        env_file: .env
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: persistence
            DISPLAY: ":0"
        volumes:
            - ./var/postgres:/var/data
            - ./cxt/cnf/postgresql.conf:/etc/postgres/conf.d/00.conf
        ports:
            #- "${EXT_PORT}:${INT_PORT}"
            - "5432:5432"
        networks:
            - networktestdata
        cap_add:
            - SYS_PTRACE
        #entrypoint:
        #    - bin/bash
        #    - -i

    #persistence2:
    #    container_name: testdata-persistence2
    #    build:
    #        context: ./cxt
    #        dockerfile: pod/mysql.dockerfile
    #    restart: always
    #    tty: true
    #    env_file: .env
    #    environment:
    #        SERVICE_TAGS: dev
    #        SERVICE_NAME: persistence2
    #        DISPLAY: ":0"
    #    volumes:
    #        - ./var/mysql:/var/lib/mysql
    #        - ./cxt/cnf/mysql.conf:/etc/my.cnf.d/00.cnf
    #    ports:
    #        #- "${EXT_PORT}:${INT_PORT}"
    #        - "3310:3306"
    #    networks:
    #        - networktestdata
    #    cap_add:
    #        - SYS_PTRACE
    #    #entrypoint:
    #    #    - bin/bash
    #    #    - -i

networks:
    networktestdata:
        driver: bridge

