name:                testdata
version:             0.1.0.0
github:              "frostbane/testdata"
license:             BSD3
author:              "frostbane"
maintainer:          "frostbane@programmer.net"
copyright:           "2020, 2021 frostbane"

#extra-source-files:
#    - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README

dependencies:
    - base >= 4.7 && < 5
    - directory >= 1.3.6.0
    - ghc-prim >= 0.5.3
    - exit-codes >= 1.0.0
    - regex-pcre >= 0.95.0
    - text >= 1.2.4
    #- ncurses >= 0.2.16
    #- gtk3 >= 0.15.5
    - optparse-generic >= 1.3.1

library:
    source-dirs: src

executables:
    testdata-exe:
        main:                Main.hs
        source-dirs:         src
        ghc-options:
            - -threaded
            - -rtsopts
            - -g3
            - -with-rtsopts=-N
            #- -optl-static
        dependencies:
            - testdata

tests:
    testdata-test:
        main:                Spec.hs
        source-dirs:         test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - testdata
